version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-java
    environment:
      - POSTGRES_DB=PasteBin
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  mongoDB:
    image: "mongo:latest"
    restart: always
    ports:
      - "27017:27017"

  app:
    build: ./
    container_name: app-java
    ports:
      - "8080:8080"

